name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: |
            --sarif-file-output=snyk.sarif
            --all-projects
            --severity-threshold=high  # Set the severity threshold as needed
            --fail-on-issues             # Fail the build if vulnerabilities are found
            --dev                        # Include dev dependencies
            # Add any other Snyk CLI options as needed
      - name: Check vulnerabilities for ZIP
        run: |
          if [ "${{ github.job }}" != "success" ]; then
            echo "Existen vulnerabilidades."
            echo "has_vulnerabilities=true" >> $GITHUB_ENV
          else
            echo "No existen vulnerabilidades."
            echo "has_vulnerabilities=false" >> $GITHUB_ENV
          fi
        id: snykcheck

      - name: Archive ZIP if code is secure
        if: env.has_vulnerabilities == 'false'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: .
          file_path: secure-code.zip
          verbose: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
