name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        id: snyk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: |
            --sarif-file-output=snyk.sarif --all-projects
            --severity-threshold=high
            --fail-on-issues
            --dev
      - name: Check vulnerabilities for ZIP
        run: |
          if [ "${{ steps.snyk.outcome }}" == "failure" ]; then
            echo "Existen vulnerabilidades. Se generará el ZIP."
            echo "has_vulnerabilities=true" >> $GITHUB_ENV
          else
            echo "No existen vulnerabilidades. No se generará el ZIP."
            echo "has_vulnerabilities=false" >> $GITHUB_ENV
          fi
        id: snykcheck
      - name: Archive ZIP if code is not secure
        if: env.has_vulnerabilities == 'false'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: .
          file_path: secure-code.zip
          verbose: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
