name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Check for vulnerabilities
        run: |
          vulnerabilities=$(echo "${{ steps.snyk.outputs.stdout }}" | grep -c 'contained vulnerable paths')
          if [ "$vulnerabilities" -gt 0 ]; then
          echo "Code is vulnerable. Not uploading zip."
          exit 1
          else
          echo "Code is secure. Proceeding to upload zip."
          fi
      - name: Archive code if secure
        if: success()
        uses: ihiroky/archive-action@v1

        with:
          root_dir: .
          file_path: secure-code.zip
          verbose: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
