name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        
        continue-on-error: true # To make sure that SARIF upload gets called
        run: |
          snyk test --sarif-file-output=snyk.sarif --all-projects
          if [ $? -eq 0 ]; then
            echo "No existen vulnerabilidades."
            echo "::set-output name=has_vulnerabilities::false"
            zip -r secure-code.zip .
          else
            echo "Existen vulnerabilidades."
            echo "::set-output name=has_vulnerabilities::true"
          fi

      - name: Archive ZIP if code is secure
        if: steps.snykcheck.outputs.has_vulnerabilities == 'false'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: .
          file_path: secure-code.zip
          verbose: true
      - name: Handle case if code is not secure
        if: steps.snykcheck.outputs.has_vulnerabilities != 'false'
        run: echo "El código no es seguro. No se genero el archivo ZIP."
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
