name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Snyk Vulnerabilities
        run: |
          if [ "${{ github.job }}" != "success" ]; then
            echo "Existen vulnerabilidades."
            echo "::set-output name=has_vulnerabilities::true"
          else
            echo "No existen vulnerabilidades."
            echo "::set-output name=has_vulnerabilities::false"
          fi
        id: snykcheck

      - name: Archive code if secure
        if: steps.snykcheck.outputs.has_vulnerabilities == 'false'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: .
          file_path: secure-code.zip
          verbose: true
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
